Bid/urls.py
from django.urls import path,re_path
from Bid.views import CreateController,DeleteController



app_name='Bid'
urlpatterns = [
    re_path(r'^$', CreateController, name='create'),
    re_path(r'^delete/$', DeleteController, name='delete' )
        
    ]

CoinOffering/urls.py
from django.contrib import admin
from django.urls import path,re_path, include
from Users.views import HomeRedirectController

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^user/', include('Users.urls', namespace='Users')),
    re_path(r'^bid/', include('Bid.urls', namespace='Bid')),
    re_path(r'^$', HomeRedirectController, name="home"),

]

Users/urls.py
from django.urls import path,re_path
from Users.views import SignUpController,SignInController,HomePageController,LogOutController



app_name='Users'
urlpatterns = [
    re_path(r'^sign-in/$', SignInController, name='sign-in'),
    re_path(r'^sign-up/$', SignUpController, name='sign-up' ),
    re_path(r'^home-page/$',  HomePageController, name='home-page'),
    re_path(r'^log-out/$',  LogOutController, name='log-out'),

    
    ]

Users/models.py
from django.db import models
from django.conf import settings


# Create your models here.


class Customer(models.Model):
    user        = models.OneToOneField(settings.AUTH_USER_MODEL,
                                    related_name='customer',
                                    on_delete=models.CASCADE)
    # created customer models cus its extendable and also seperate from admin
    

Users/forms.py
from django import forms
from django.contrib.auth.models import User




class CustomerForm(forms.Form):
    first_name = forms.CharField(max_length=200,       
                             label=False,
                             widget=forms.TextInput(
                               attrs={'id':'first_name',
                                      'class': '',
                                      'placeholder':'First Name'}))
    last_name = forms.CharField(max_length=200,       
                             label=False,
                             widget=forms.TextInput(
                               attrs={'id':'last_name',
                                      'class': '',
                                      'placeholder':'Last Name'}))
    username = forms.CharField(max_length=20,       
                             label=False,
                             widget=forms.TextInput(
                               attrs={'id':'username',
                                      'class': '',
                                      'placeholder':'Username'}))
    email    = forms.EmailField(max_length=250,
                                label =False,
                                widget=forms.EmailInput(
                                      attrs={'id':'email',
                                            'class': '',
                                            'placeholder':'E-mail'}))

    password = forms.CharField(max_length=30,
                               label=False,
                               widget=forms.PasswordInput(
                                      attrs={'id':'password',
                                            'placeholder':'Enter password',
                                            'class':''}))
    password2 = forms.CharField(max_length=30,
                               label=False,
                               widget=forms.PasswordInput(
                                      attrs={'id':'password2',
                                            'placeholder':'Repeat password',
                                            'class':''}))

    def clean_email(self):
        # cd == Cleaned_data
        cd = self.cleaned_data.get('email')
        cd = cd.lower()
        user = User.objects.filter(email=cd).exists()
        if user:
            raise forms.ValidationError('This e-mail address is already registered to another account')
        return cd



    def clean_username(self):
        cd = self.cleaned_data.get('username')
        cd = cd.lower()
        if len(cd) < 6:
            raise forms.ValidationError("Username must contain up to 6 characters")
        if ' ' in cd:
            raise forms.ValidationError("A blank space can not be included as part of username")
        user = User.objects.filter(username=cd).exists()
        if user:
            raise forms.ValidationError('Username is already taken. Please choose another username')
        return cd

  

    def clean(self):
        cleaned_data = super(CustomerForm, self).clean()
        first_password = self.cleaned_data.get('password')
        second_password = self.cleaned_data.get('password2')
        if first_password != second_password:
            self.add_error('password',"Passwords did not match")
        return cleaned_data



class SignInForm(forms.Form):
    
    email    = forms.EmailField(max_length=250,
                                label =False,
                                widget=forms.EmailInput(
                                      attrs={'id':'email',
                                            'class': '',
                                            'placeholder':'E-mail'}))
    password = forms.CharField(max_length=30,
                               label=False,
                               widget=forms.PasswordInput(
                                      attrs={'id':'password',
                                            'placeholder':'Enter password',
                                            'class':''}))
    def __init__(self,*args,**kwargs):
        super(SignInForm,self).__init__(*args,**kwargs)

    def clean_email(self):
        # cd == Cleaned_data
        cd = self.cleaned_data.get('email')
        cd = cd.lower()
        user = User.objects.filter(email=cd).exists()
        if not user:
            raise forms.ValidationError('Email address and password did not match')
        return cd
    def clean(self):
        cleaned_data = super(SignInForm, self).clean()
        return cleaned_data
  

   

Users/views.py
from django.shortcuts import render,redirect
from Users.forms import CustomerForm,SignInForm
from django.http import HttpResponseRedirect
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.urls import reverse
from django.contrib.auth import login,logout
from django.contrib.auth.models import User
from Users.models import Customer
from Coins.models import Coin


from django.contrib.auth.decorators import login_required



# Create your views here.

def SignUpController(request):
	if request.method == "POST":
		post_form = CustomerForm(request.POST)
		if post_form.is_valid():
			cd = post_form.cleaned_data
			user = User.objects.create_user(username=cd['username'],
			        						password=cd['password'],
			      				  			first_name = cd['first_name'],
			        						last_name=cd['last_name'],
			        						email=cd['email'])
			Customer.objects.create(user=user)
			login(request,user)
			request.session["new"] = True
			return HttpResponseRedirect(reverse('Users:home-page'))
		else:
			return render(request,'Users/sign_up.html',{'form':post_form})
	else:
		form = CustomerForm()
		return render(request,'Users/sign_up.html',
                          {'form':form})


def SignInController(request):
	if request.method == "POST":
		post_form = SignInForm(request.POST)
		if post_form.is_valid():
			cd = post_form.cleaned_data
			user = User.objects.get(email=cd['email'])
			checker = user.check_password(cd['password']) 
			if checker:
				login(request, user)
				return HttpResponseRedirect(reverse('Users:home-page'))
			else:
				post_form.add_error('email','Email and password did not match')
				return render(request,'Users/sign_in.html',
                        {'form':post_form})
		else:
			return render(request,'Users/sign_in.html',
                          {'form':post_form})
	else:
		if request.user.is_authenticated:
			return HttpResponseRedirect(reverse('Users:home-page'))
		form = SignInForm()
		return render(request,'Users/sign_in.html',
                          {'form':form})
def LogOutController(request):
	logout(request)
	return HttpResponseRedirect(reverse('Users:sign-in'))
		
@login_required
def HomePageController(request):
	customer = request.user.customer
	coin=Coin.objects.get(name="MillionToken")
	try:
		bid = customer.bid
	except ObjectDoesNotExist:
		bid = False

	return render(request,'Users/home_page.html',
											{'coin':coin,
											'bid':bid})


def HomeRedirectController(request):
	return HttpResponseRedirect(reverse('Users:sign-in'))

Users/templates/Users/base.html
{% load static %}
<!DOCTYPE html>
<html lang = "en">
<head>
	<meta charset="utf-8">
	<title > DigiCentra </title>
	<meta name="theme-color" content="#ffffff">
	<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=no ">
	{% block head %}{% endblock %}
</head>
<body>
	
	


	{% block content %}{% endblock %}


</body>
</html>

Users/templates/Users/home_page.html
{% extends 'Users/base.html' %}
{% block content %}

<style type="text/css">
    .lorange{
        color: orange;
        /*font-weight: bold;*/
        text-align: center;
        font-size: 130%;
    }
    .lblue{
        color: blue;
        /*font-weight: bold;*/
    }
    .cover{
        border-radius: 20px;
        text-align: unset;
        border-color: rgb(220,220,220);
        box-shadow: 0px 1px 1px 1px rgba(0, 0, 0, 0.2);
    }
</style>
 <br>
<div class="cover">
<br><br>
<div class="lorange lblue">Hello {{request.user.first_name}},</div>

<br>
<div class="lorange">Invest in Million Token Today</div>
<br>
{% if bid == False %}
<div class="lorange">  You have no active bid. Kindly bid for one <a href="{% url 'Bid:create' %}">right here</a></div>

{% else %}
{% if bid.processed %}
{% if bid.successful %}
<div class="lorange"> Your bid was successful!!!
<br><br><br>
<div class="lblue">
<div>number of tokens received: &emsp;&emsp;<span id="number_of_tokens_allotted">{{bid.successful.number_of_tokens_allotted}}</span></div><br>

<div>number of tokens bid for: &emsp;&emsp;<span id="number_of_tokens">{{bid.number_of_tokens}}</span></div><br>
<div>Price per token : &emsp;&emsp;<span id="price_per_token">{{bid.price_per_token}}</span></div><br>
<div>Total Due : &emsp;&emsp;<span id="total_due">{{bid.successful.total_due}}</span></div>
</div>
</div>
{% else %}
<div class="lorange"> Sorry, your bid was unsuccessful</div><br><br><br>
{% endif %}

{% else %}
<div class="lorange"> You have an active bid for MillionToken 
<br><br><br>
<div class="lblue" >
<div>number of tokens bid for: &emsp;&emsp;<span id="number_of_tokens">{{bid.number_of_tokens}}</span></div><br>
<div>Price per token : &emsp;&emsp;<span id="price_per_token">{{bid.price_per_token}}</span></div>
</div>
</div>
{% endif %}
<br><br><br>
<div class="lorange"><a href="{% url 'Bid:delete' %}"><button>DELETE</button></a></div>

{% endif %}
<br>


<br><br>
<div class="lorange"><a href="{% url 'Users:log-out' %}"><button>LOG OUT</button></a></div>

</div>
<br><br><br><br><br><br>
<script type="text/javascript">
    function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
var list = [document.getElementById('total_due') || false,
        document.getElementById('price_per_token') || false,
        document.getElementById('number_of_tokens') || false,
        document.getElementById('number_of_tokens_allotted') || false,
        ]
for (each in list){
    if (each){
        list[each].innerHTML = numberWithCommas(parseInt(list[each].innerHTML))
    }
}
</script>
{% endblock %}

Users/templates/Users/sign_in.html
{% extends 'Users/base.html' %}
{% block content %}
{% load static %}

 <br>
<div class="menubuttons" style="border-radius: 20px;text-align: unset;font-weight: normal;border-color: rgb(220,220,220);box-shadow: 0px 1px 1px 1px rgba(0, 0, 0, 0.2);">

<br><br>
<div style="color: orange;font-weight: bold;text-align: center;font-size: 130%;"> Log In </div>
<br>
<div style="color: grey;text-align:center;" class="content">
	Welcome to DigiCentra<br> Please log in up here
</div><br><br>
<div style="width: 20%;margin: auto;">
<form action="{% url 'Users:sign-in' %}" method="POST">
						{{ form.as_p }}
					{% csrf_token %}
<button type="submit" style="background-color:orange;color: white;font-size: 100%;font-weight: bold;" class="linestyle" >Log In</button>
      
</form>
<br><br><br>
<div>Don't have an account? <a href="{% url 'Users:sign-up' %}">sign-up</a>
</div>
<br><br><br><br><br><br>
</div>

</div>

{% endblock %}

Users/templates/Users/sign_up.html
{% extends 'Users/base.html' %}
{% block content %}
{% load static %}

 <br>
<div class="menubuttons" style="border-radius: 20px;text-align: unset;font-weight: normal;border-color: rgb(220,220,220);box-shadow: 0px 1px 1px 1px rgba(0, 0, 0, 0.2);">

<br><br>
<div style="color: orange;font-weight: bold;text-align: center;font-size: 130%;"> Sign Up </div>
<br>
<div style="color: grey;text-align:center;" class="content">
	Welcome to DigiCentra<br> Please Sign up here
</div><br><br>
<form action="{% url 'Users:sign-up' %}" method="POST">
						{{ form.as_p }}
					{% csrf_token %}
<button type="submit" style="background-color:orange;color: white;font-size: 100%;font-weight: bold;" class="linestyle" >Sign Up</button>
      
</form>
<br><br><br>
</div>


{% endblock %}